name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
    
    - name: Show Xcode version
      run: xcodebuild -version
    
    - name: Build
      run: |
        xcodebuild -project ObsiVoice.xcodeproj \
          -scheme ObsiVoice \
          -configuration Debug \
          -destination 'platform=macOS' \
          clean build \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
    
    - name: Install xcpretty
      run: gem install xcpretty
    
    - name: Run Tests
      run: |
        xcodebuild test -project ObsiVoice.xcodeproj \
          -scheme ObsiVoice \
          -destination 'platform=macOS' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          | xcpretty --report junit --output test-results.xml
      continue-on-error: true
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results.xml
    
    - name: Archive build artifacts
      run: |
        cd build/Debug
        zip -r ../../VoiceLogger.zip ObsiVoice.app
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: VoiceLogger-Debug
        path: VoiceLogger.zip

  lint:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install SwiftLint
      run: brew install swiftlint
    
    - name: Run SwiftLint
      run: swiftlint lint --reporter github-actions-logging
      continue-on-error: true